### PR TITLE
Add local storage option for remember me

### PR DESCRIPTION
**Pull request by iHiD**
I'm writing a PhoneGap app. All the devices I support will have local storage and I would rather not have the $.cookie dependency. Cookies also do not work through Chrome on single-file applications without using special flags, so that's another reason for this.

I've added a config option and refactored out the get/set/remove methods for the cookie. Let me know if you need anything changing.

(P.S. I'm managed to actually edit the source this time :))

### CODE REVIEW

**Comment by heartsentwined** [comment]
Thanks for this PR. Do you think we should remove the bundled `$.cookie` over at the `ember-auth-rails` pack too?

So far it seems `$.cookie` is the majority use case.

**Comment by iHiD** [comment]
I've not using this with rails so it's not been an issue for me. Could you somehow make it a conditional within Sprockets that if there is the localstorage setting in an initializer, then it doesn't include the file. I've never played with Sprockets so I'm not sure if that's possible?

**Comment by heartsentwined** [comment]
I'll let it stay with the package for the time being, reasoning that:
1. cookie users are bearing an "overhead" of localStorage code anyway
2. `$.cookie` is not that big

**Comment by heartsentwined** [comment]
API introduced in this PR has been changed in the `3.0` branch.

Relevant section from the upgrade guide in the [Changelog](https://github.com/heartsentwined/ember-auth/blob/master/CHANGELOG.md):

> ### Auth.Config.rememberUsingLocalStorage
> 
> Before:
> 
> ``` coffeescript
> Auth.Config.reopen { rememberUsingLocalStorage: false }
> Auth.Config.reopen { rememberUsingLocalStorage: true }
> ```
> 
> After:
> 
> ``` coffeescript
> Auth.Config.reopen { rememberStorage: 'cookie' } # or omit - default value
> Auth.Config.reopen { rememberStorage: 'localStorage' }
> ```

**Pull request merged**
