### PR TITLE
Handle tokenKey injection for FormData

### PR DESCRIPTION
**Pull request by mastropinguino**
Hello,
using a custom ajax request eg.

``` js
// ajax based upload

var fd = new FormData();
fd.append('fieldname', $('#file').get(0).files[0]);

Auth.ajax({
  url: '/test_upload',
  data: fd,
  contentType: false,
  cache: false,
  processData: false
});
```

ajax function in ember-auth will match 'object' case in switch and will add property to FormData instead it should add tokenKey with proper "append" method.

Hoping, could be useful

### CODE REVIEW

**Comment by heartsentwined** [comment]
Thanks for the PR. Useful and innocent-looking, but I'll unit-test it before merging.

**Comment by heartsentwined** [comment]
Merge into master - but not yet into new version release, pending unit tests.

**Comment by heartsentwined** [comment]
Discovered something when writing unit tests for this feature: there is no way to inspect a `FormData` object, nor replace, nor delete, any of its elements.

If the auth token in question is already set, then calling `.append()` will not override the existing auth token; it actually creates _another_ entry, with the _same key_, in the `FormData` object.

While this may not be relevant for your use case, when another dev wants to override the default auth token - for whatever reason - one will find that it "does not work".

I can't find a workaround for this at the moment, so I'll just note it here as a caveat.

**Comment by heartsentwined** [comment]
For reference, the current `ember-auth` behavior for all the other token location formats is to preserve any existing values at the declared keys. This allows devs to override whatever `ember-auth` sets, useful for custom logic.

**Comment by mastropinguino** [comment]
You are right.
I think that better thing to do is to rollback my PR, because it can add unwanted behaviours.
So, I will threat this issue as my custom-behaviour and wrap Auth.ajax with my function that will do what I do in PR.
Thanks ;)

**Comment by heartsentwined** [comment]
We can let it stay though, since `FormData` is not the default, if a dev explicitly chooses to use it, we can assume that he knows what he is doing :)

Or hope that his googling will end up here.

**Comment by heartsentwined** [comment]
And that it actually takes double the effort for the unwanted behavior to manifest:
1. that the dev uses `FormData`
2. either that the dev tries to override the auth token, or that he somehow sends an variable with same key as auth token.

The last case is comical though, since the behavior does not make sense. The auth token is gone? (hence protected resource inaccessible) Or the variable is gone? (corrupted data)

**Comment by heartsentwined** [comment]
Anyway, for now `FormData` is okay, since it only affects an edge case. If I get into more trouble with `FormData` though, I'll have to remove the PR.

**Comment by mastropinguino** [comment]
What you think about enable FormData injection behaviour via settings?
Eg.

``` coffee
Auth.Config.reopen
  requestTokenLocation: 'param' # or omit this line - this is the default value
  tokenKey: 'auth_token'
  tokenKeyInFormData: true # default true 
```

In this way my patch will be activated only when tokenKeyInFormData = true and when false all things goes as Ember.Auth does before.

**Comment by heartsentwined** [comment]
There would be no need. All the patch does is to provide a more specific override for `object`s.

Scenarios:
1. A dev using `FormData` but not turning on the patch would get errors, so he must turn it on anyway.
2. A dev not using `FormData` will not feel the effect of the patch at all, even if he turns it on, because the patch detects `FormData` objects before falling through to general objects.

But the patch itself already detects `FormData` instances, so I think this is superfluous. In any case, even if this config is added, it would not solve the `FormData` limitation.

I'm glad that you took the effort to try to minimize the downside of the patch though, just that this solution does nothing, IMHO.

**Comment by mastropinguino** [comment]
Okay.

**Comment by heartsentwined** [comment]
@mastropinguino this PR has been included in `5.x` release, albeit with the caveats we have discussed here.

**Comment by mastropinguino** [comment]
Thanks ;)

**Pull request merged**
