### PR TITLE
Do not stringify settings.data in ember-model module

### PR DESCRIPTION
**Pull request by maoe**
This is a fix for #78. I haven't been able to use this code anywhere. So if anyone could try it, that would be great.

### CODE REVIEW

**Comment by flynfish** [comment]
I'm not sure why the content type has to be set, but that line causes it to fail now.

If you change 'contentType' to 'Content-Type' then everything works correctly, except that passing in something other that application/json doesn't overwrite the content type anyways.

**Comment by flynfish** [comment]
@heartsentwined @maoe 
Ok, after further debugging I found the cause of the issue. Ignore my previous comment about changing it to "Content-Type". 

If we set the `contentType` where you are setting it in your pull request, then `Em.Auth.Request.Jquery#send` will never `JSON.stringify` `settings.data` and settings is just extended ->

```
if settings.data && !settings.contentType?
  if settings.type? && settings.type.toUpperCase() != 'GET'
    settings.data   = JSON.stringify(settings.data)
  if settings.type?.toUpperCase() != 'GET'
    def.contentType = 'application/json; charset=utf-8'
settings = $.extend def, settings
```

`Em.Auth.Request.Jquery#send` is already doing the `GET` check that your PR is doing and setting the content type so it doesn't look like we really need that.

**Comment by heartsentwined** [comment]
Merged over at #95.

**Comment by maoe** [comment]
@flynfish Thanks for spotting this.

**Pull request merged**
